version: '3'
services:
  teamdb:
    build:
      context: ./Dockerfiles/db
    image: teamdb
    container_name: teamdb
    ports:
      - "3306:3306"
    volumes:
      - teamdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=teamdbpass

  teamcache1:
    image: memcached
    ports:
      - "11211:11211"

  teamrmq1:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  teamapp:
    build:
      context: ./Dockerfiles/app
    image: teamapp
    container_name: teamapp
    ports:
      - "8080:8080"
    volumes: 
      - teamappdata:/usr/local/tomcat/webapps

  teamweb:
    build:
      context: ./Dockerfiles/web
    image: teamweb
    container_name: teamweb
    ports:
      - "80:80"
volumes:
  teamdbdata: {}
  teamappdata: {}
